In [ ]:
#installing the dependencies 
!pip install google-cloud-vision==0.29.0
! pip install pdf2image
! pip install poppler-utils
! apt-get install poppler-utils 

     |████████████████████████████████| 81kB 3.9MB/s 
     |████████████████████████████████| 51kB 5.1MB/s 
ERROR: google-cloud-translate 1.5.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.6.0, but you'll have google-api-core 0.1.4 which is incompatible.
ERROR: google-cloud-language 1.2.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.6.0, but you'll have google-api-core 0.1.4 which is incompatible.
ERROR: google-cloud-firestore 1.7.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.14.0, but you'll have google-api-core 0.1.4 which is incompatible.
ERROR: google-cloud-datastore 1.8.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.6.0, but you'll have google-api-core 0.1.4 which is incompatible.
ERROR: google-cloud-core 1.0.3 has requirement google-api-core<2.0.0dev,>=1.14.0, but you'll have google-api-core 0.1.4 which is incompatible.
ERROR: google-cloud-bigquery-storage 1.1.0 has requirement google-api-core[grpc]<2.0.0dev,>=1.14.0, but you'll have google-api-core 0.1.4

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.
Need to get 154 kB of archives.
After this operation, 613 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 poppler-utils amd64 0.62.0-2ubuntu2.12 [154 kB]
Fetched 154 kB in 1s (116 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 160975 files and directories currently installed.)
Preparing to unpack .../poppler-utils_0.62.0-2ubuntu2.12_amd64.deb ...
Unpacking poppler-utils (0.62.0-2ubuntu2.12) ...
Setting up poppler-utils (0.62.0-2ubuntu2.12) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...


In [ ]:
#testing GPU
!apt-get install nvidia-cuda-toolkit
!pip3 install numba

import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/lib/nvidia-cuda-toolkit/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/lib/x86_64-linux-gnu/libnvvm.so"

from numba import cuda
import numpy as np
import time

@cuda.jit
def hello(data):
    data[cuda.blockIdx.x, cuda.threadIdx.x] = cuda.blockIdx.x

numBlocks = 5
threadsPerBlock = 10

data = np.ones((numBlocks, threadsPerBlock), dtype=np.uint8)

hello[numBlocks, threadsPerBlock](data)

print(data)

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  cpp-6 fonts-dejavu-core fonts-dejavu-extra g++-6 gcc-6 gcc-6-base
  libaccinj64-9.1 libasan3 libatk-wrapper-java libatk-wrapper-java-jni
  libcublas9.1 libcudart9.1 libcufft9.1 libcufftw9.1 libcuinj64-9.1
  libcurand9.1 libcusolver9.1 libcusparse9.1 libgail-common libgail18
  libgcc-6-dev libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libnppc9.1
  libnppial9.1 libnppicc9.1 libnppicom9.1 libnppidei9.1 libnppif9.1
  libnppig9.1 libnppim9.1 libnppist9.1 libnppisu9.1 libnppitc9.1 libnpps9.1
  libnvblas9.1 libnvgraph9.1 libnvrtc9.1 libnvtoolsext1 libnvvm3
  libstdc++-6-dev libthrust-dev libvdpau-dev libxxf86dga1 nvidia-cuda-dev
  nvidia-cuda-doc nvidia-cuda-gdb nvidia-profiler nvidia-visual-profiler
  openjdk-8-jre openjdk-8-jre-headless x11-utils
Suggested packages:
  gcc-6-locales g++-6-multilib gcc-6-doc libstdc++6-6-dbg gcc-6-multilib
  libgc

/usr/local/lib/python3.7/dist-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/lib/x86_64-linux-gnu/libnvvm.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/usr/local/lib/python3.7/dist-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/lib/nvidia-cuda-toolkit/libdevice.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))


[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]]


In [ ]:
#including the dependencies
from PIL import Image
import numpy as np
import pandas as pd
import PIL
import cv2
from pdf2image import convert_from_path
import base64
import numpy as mau
%cd /content/drive/MyDrive/Thiru3

/content/drive/MyDrive/Thiru3


In [ ]:
#Converting pdf to separate image files 
images = convert_from_path('input your pdf path ')
count = 0 
for i in range(len(images)):
   
        images[i].save('page'+ str(i+1) +'.jpg', 'JPEG')
        count+=1

In [ ]:
count

26

In [ ]:
#preprocessing of image files 

for k in range(4,count-2):


  B = 'input your image path '+str(k)+'.jpg'
  im = Image.open(B)
  im = im.resize((4000, 4882), PIL.Image.LANCZOS)
  im = cv2.bilateralFilter(np.array(im, dtype= np.uint8),9,75,75)
  im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
  im = cv2.adaptiveThreshold(np.array(im,dtype=np.uint8), 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 31, 15)
  #segmentation of images after preprocessing 
  im = Image.fromarray(im)
  crop_rectangle_nm = (170,305, 1010, 610)
  for i in range(0,10):

    for j in range(0,3):
      
      Crop = im.crop(crop_rectangle_nm)
      Crop.save('page'+str(k)+'crop'+str(i)+str(j)+'.jpg')
      

      crop_rectangle_nm = tuple(np.add(crop_rectangle_nm,(1215,0,1215,0)))
    crop_rectangle_nm = tuple(np.subtract(crop_rectangle_nm,(3645,0,3645,0)))
    crop_rectangle_nm = tuple(np.add(crop_rectangle_nm,(0,405,0,410)))

In [ ]:
#Extraction of data segment 
import os, io
from google.cloud import vision
import pandas as pd

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r"Your API key"

client = vision.ImageAnnotatorClient()
name = []
father = []
hno = []
age = []
gen = []
grel = []
filename = []
n = []
f = []
g = []
a = []
gr = []
h = []
inst = []
for k in range(4,count-2):


  for i in range(0,10):

    for j in range(0,3):
        
      
      file_name = 'page'+str(k)+'crop'+str(i)+str(j)+'.jpg'
      image_path = f'/content/drive/MyDrive/Thiru3/{file_name}'

      with io.open(image_path, 'rb') as image_file:
          content = image_file.read()


      image = vision.types.Image(content=content)

      response = client.text_detection(image=image)  
      df = pd.DataFrame(columns=['locale', 'description'])

      texts = response.text_annotations
      for text in texts:
          df = df.append(
              dict(
                  locale=text.locale,
                  description=text.description
              ),
              ignore_index=True
          )

      try:
        B = df['description'][0]
      except IndexError:
        continue
      details = B.splitlines()
      B = mau.asarray(details,dtype=object)
      B = B[B != ('பெயர்')]
      print(len(B))
      print(B)
      if len(B) == 4:
        try:
          n = B[0].split(":")[1]
          gr = B[1].split(":")[0]
          f = B[1].split(":")[1]
          h = B[2].split(':')[1]
          mm = B[3].split(":")
          a = mm[1]
          g = mm[2]  
        except IndexError:
          try:
            n = B[3]
            gr = B[0].split(":")[0]
            f = B[0].split(":")[1]
            h = B[1].split(':')[1]
            mm = B[2].split(":")
            a = mm[1]
            g = mm[2]  
          except IndexError:
            try:
              n = B[2]
              gr = B[0].split(":")[0]
              f = B[0].split(":")[1]
              h = B[1].split(':')[1]
              mm = B[3].split(":")
              a = mm[1]
              g = mm[2]
            except IndexError:
              n = B[0].split(":")[1]
              gr = B[1]
              f = 'not detected'
              h = 'not detected'
              mm = B[3].split(":")
              a = mm[0]
              g = mm[1]



      if len(B) == 5:
        try:
          n = B[0].split(":")[1]
          gr = B[1]
          f = B[2]
          h = B[3].split(":")[1]
          mm = B[4].split(":")
          a = mm[1]
          g = mm[2]
        except IndexError:

          try:
            n = B[0].split(":")[1]
            gr = B[1].split(":")[0]
            f = B[1].split(":")[1]
            h = B[2].split(":")[1]
            mm = B[3].split(":")
            a = mm[1]
            if B[4].split(":")[1] == ' ஆண்'or' பெண்':
              g = B[4]
          except IndexError:
            try:
              
              n = B[0].split(":")[1]
              gr = B[1].split(":")[0]
              f = B[1].split(":")[1]
              h = B[2].split(":")[1]
              try:
                
                mm = B[3].split(":")
                a = mm[1]
                if B[4].split(":")[1] == ' ஆண்'or' பெண்':
                  g = B[4]
              except IndexError:
                if B[3]=='வயது':
                  a = B[3]
                  g = B[4].split(":")[1]
            except IndexError:
              
                
                    try:
                      n = B[0].split(":")[1]
                      gr = B[1].split(":")[0]
                      f = B[1].split(":")[1]
                      h = B[2].split(":")[1]
                      try:
                      
                        mm = B[3].split(":")
                        a = mm[1]
                        if B[4].split(":")[1] == ' ஆண்'or' பெண்':
                          g = B[4]
                      except IndexError:
                        if B[3]=='வயது':
                          a = B[3]
                          g = B[4].split(":")[1]   
                    except IndexError:
                      if (B[i] == 'DELEFED' or 'DELETED' for i in range(0,4)):
                        n = 'deleted' 
                        gr = 'deleted'
                        f = 'deleted'
                        a = 'deleted'
                        g = 'deleted'
                        h = 'deleted'       
        if len(B) == 6:
          try:
            n = B[0].split(":")[1]
            gr = B[1]
            h = B[2].split(":")[1]
            mm = B[3].split(":")
            a = mm[1]
            f = B[4].split(":")[1]
            g = B[5]
          except IndexError:
            try:

              n = B[0].split(":")[1]
              gr = B[1]
              f = B[2]
              h = B[5].split(":")[1]
              mm = B[4].split(":")
              a = mm[1]
              
              g = mm[2]
            except IndexError:
              try:

                n = B[0].split(":")[1]
                gr = B[1]
                f = B[2]
                h = B[5].split(":")[1]
                mm = B[4].split(":")
                a = mm[1]         
                g = mm[2]
              except IndexError:
                try:
                  if (B[i] == 'DELEFED' or 'DELETED' for i in range(0,4)):

                    n = 'deleted' 
                    gr = 'deleted'
                    f = 'deleted'
                    a = 'deleted'
                    g = 'deleted'
                    h = 'deleted'  
                except IndexError:

                  n = B[0].split(":")[1]
                  gr = B[1]
                  f = B[2]
                  h = B[5].split(":")[1]
                  mm = B[4].split(":")
                  a = mm[1]         
                  g = mm[2]





                  

      name.append(n)
      father.append(f)
      hno.append(h)
      age.append(a)
      gen.append(g)
      grel.append(gr)
      filename.append(inst)

        
      
      
  df = pd.DataFrame(np.column_stack([name,grel, father, hno,age,gen]),columns=['name','g_relation', 'guardian', 'hno','age','gen'])
  df.to_excel(str(k)+".xlsx",index = False)
  

4
['பெயர்: செல்வி' 'கணவர் பெயர்: அன்பு' 'வீட்டு எண்: 9'
 'வயது: 41 பாலினம் : பெண்']
4
['பெயர்: சுந்தரி' 'கணவர் பெயர்: ஜெயகாந்தன்' 'வீட்டு எண்: 10'
 'வயது: 79 பாலினம் : பெண்']
4
['பெயர்: பத்மாவதி' 'கணவர் பெயர்: தணிகைமலை' 'வீட்டு எண்: 10'
 'வயது: 64 பாலினம் : பெண்']
4
['பெயர்: சுரேஷ்' 'தந்தை பெயர்: தணிகைமலை' 'வீட்டு எண்: 10'
 'வயது: 46 பாலினம் : ஆண்']
4
['பெயர்: ஜெயகாந்தன்' 'தந்தை பெயர்: தணிகைமலை' 'வீட்டு எண்: 10'
 'வயது: 45 பாலினம் : ஆண்']
4
['பெயர்: ஸ்ரீதர்' 'தந்தை பெயர்: தணிகைமலை' 'வீட்டு எண்: 10'
 'வயது: 39 பாலினம் : ஆண்']
4
['பெயர்: பாஸ்கர்' 'தந்தை பெயர்: தணிகைமலை' 'வீட்டு எண்: 10'
 'வயது: 37 பாலினம்: ஆண்']
4
['பெயர்: ஜோதிலட்சமி' 'கணவர் பெயர்: சங்கர்' 'வீட்டு எண்: 11'
 'வயது: 43 பாலினம் : பெண்']
4
['பெயர்: பூரணி .வ' 'தந்தை பெயர்: வடிவேல் .தா' 'வீட்டு எண்: 3/1'
 'வயது: 22 பாலினம் : பெண்']
4
['பெயர்: சுதா' 'கணவர் பெயர்: வெங்கடேசன்' 'வீட்டு எண்: 3-4'
 'வயது: 29 பாலினம் : பெண்']
4
['பெயர்: வெங்கடேசன்' 'தந்தை பெயர்: சுப்பிரமணி' 'வீட்டு எண்: 3-4A'
 'வயது: 34 பாலினம் : ஆண்']
4
['பெயர்: நதி

KeyboardInterrupt: ignored